### ISSUE TITLE
jekyll build produces wrong assets location

### ISSUE THREAD

**Issue by mwang99** [arnolds/pineapple#6]
jekyll points to `/assets/css/css/` instead of just `/assets/css/` when using `jekyll build`

tested on nginx and local python server, both having this issue. This issue also seems non-existent when using `jekyll serve` 

method of downloading was 
`git clone https://github.com/arnolds/pineapple`
`cd pineapple`
`jekyll build`

and then checking the website, as well as a local python simple http server.

**Comment by arnolds** [comment]
@mwang99 

I couldn't replicate the issue on my machine. 

```
Jekyll | 3.7.3
Bundler | 1.16.1
Python | 2.7.17
PHP | 7.1.32
```

I ran the site through `jekyll serve`, `python -m SimpleHTTPServer`, `php -S localhost:8000`, and the site appears correctly. It's likely down to your server configuration.

What is your version of Jekyll, and Bundler?

**Comment by mwang99** [comment]
Hi, it turns outI was doing something incorrectly with the config file. I
must've forgotten to take down the issue. My apologies.

**Comment by arnolds** [comment]
@mwang99 No worries, glad to hear it was sorted
