### ISSUE TITLE
LinkedIn Title incorrect

### ISSUE THREAD

**Issue by arnaumanyosa** [arnolds/pineapple#7]
https://github.com/arnolds/pineapple/blob/c534c219dcb30d2db6899594b899523b0c37cf77/_includes/footer.html#L10

Title should be `LinkedIn`

**Comment by arnolds** [comment]
Thanks for reporting. That's been fixed in commit: https://github.com/arnolds/pineapple/commit/e76f45b7e4ff94a487cb7489fd886d0d69efe522
